stages:
  - build
  - deploy
  - cleanup

build:
  stage: build
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm run build
    - docker build -t registry.digitwalk.com/track-script .
    - docker push registry.digitwalk.com/track-script
  tags:
    - build
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker-compose pull
    - docker-compose up -d
  only:
    - master
  tags:
    - stage

cleanup:
  stage: cleanup
  script:
    - EMPTYIMAGE=$(docker images | awk '{print $1, $3}' | grep '^<none>' | awk '{print $2}') sh -c 'if [ ! -z "$EMPTYIMAGE" ]; then docker rmi $EMPTYIMAGE; fi'
  only:
    - master
  tags:
    - stage
  allow_failure: true
